Feat/new landing page
etournity/etournity pull request #52
Opened 2023-07-15 08:03 UTC by AmNat789

## Proposed changes

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/etournity/etournity/#contributing) doc
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Created New Landing Page

2023-07-15 08:07 UTC, AmNat789 commented
Do not merge until new loading animation is added
(Still needs to be designed)

2023-07-23 12:27 UTC, FLuplow requested changes
I really like the approach of extracting all the segments into their own files.

Overall relly good, but there are a few things that still should be thought over.

Do we really need to use .mp4's in the header and for the twitch clips? I think .gif would be a better format since we don't use sound there.

Our convention for size measurements is `rem`, so it would be nice to change all `px` values over to `rem`.

2023-07-23 12:27 UTC, FLuplow commented on packages/client/utils/useVideosLoaded.ts
This seems to be unused. Are there plans to use this later?

2023-07-24 08:09 UTC, AmNat789 commented on packages/client/components/landingPage/header.tsx
> +        </video>
I think 2 videos should be used, because the second video needs to be preloaded

2023-07-30 09:12 UTC, FLuplow approved these changes

2023-07-30 09:58 UTC, merged